<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Chapter 1 | bat thesis</title>
  <meta name="description" content="2 Chapter 1 | bat thesis" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Chapter 1 | bat thesis" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Chapter 1 | bat thesis" />
  
  
  

<meta name="author" content="Kaushik Narasimhan" />


<meta name="date" content="2019-10-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="chapter-2.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.46.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.46.1/plotly-latest.min.js"></script>



<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MS Thesis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Questions and Objectives</a></li>
<li class="chapter" data-level="2" data-path="chapter-1.html"><a href="chapter-1.html"><i class="fa fa-check"></i><b>2</b> Chapter 1</a><ul>
<li class="chapter" data-level="2.1" data-path="chapter-1.html"><a href="chapter-1.html#species-accumulation-curves"><i class="fa fa-check"></i><b>2.1</b> Species Accumulation Curves</a></li>
<li class="chapter" data-level="2.2" data-path="chapter-1.html"><a href="chapter-1.html#rarefaction-using-vegan"><i class="fa fa-check"></i><b>2.2</b> Rarefaction using Vegan</a></li>
<li class="chapter" data-level="2.3" data-path="chapter-1.html"><a href="chapter-1.html#deriving-simpsons-diversity-index"><i class="fa fa-check"></i><b>2.3</b> Deriving Simpson’s Diversity Index</a></li>
<li class="chapter" data-level="2.4" data-path="chapter-1.html"><a href="chapter-1.html#lets-make-a-whittaker-plot"><i class="fa fa-check"></i><b>2.4</b> Lets make a Whittaker plot</a></li>
<li class="chapter" data-level="2.5" data-path="chapter-1.html"><a href="chapter-1.html#hypothesis-1-there-is-no-difference-in-bat-species-diversity-abundance-richness-between-forest-types"><i class="fa fa-check"></i><b>2.5</b> Hypothesis 1: There is no difference in bat species diversity, abundance, richness between forest types</a></li>
<li class="chapter" data-level="2.6" data-path="chapter-1.html"><a href="chapter-1.html#hypothesis-2-there-is-no-difference-in-number-of-feeding-guilds-between-forest-type"><i class="fa fa-check"></i><b>2.6</b> Hypothesis 2: There is no difference in number of feeding guilds between forest type</a></li>
<li class="chapter" data-level="2.7" data-path="chapter-1.html"><a href="chapter-1.html#hypothesis-3-there-is-no-relationship-between-abundances-of-individual-species-and-forest-type"><i class="fa fa-check"></i><b>2.7</b> Hypothesis 3: There is no relationship between Abundances of Individual species and forest type</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter-2.html"><a href="chapter-2.html"><i class="fa fa-check"></i><b>3</b> Chapter 2</a><ul>
<li class="chapter" data-level="3.1" data-path="chapter-2.html"><a href="chapter-2.html#hypothesis-4-no-difference-in-captures-by-height-as-a-result-of-forest-type"><i class="fa fa-check"></i><b>3.1</b> Hypothesis 4: No difference in captures by height as a result of forest type</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">bat thesis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter-1" class="section level1">
<h1><span class="header-section-number">2</span> Chapter 1</h1>
<div id="species-accumulation-curves" class="section level2">
<h2><span class="header-section-number">2.1</span> Species Accumulation Curves</h2>
<p>Species accumuluation curve. Notice that it does not plateau.
<img src="MSthesisBook_files/figure-html/Species%20Accumulation%20Curves-1.png" width="672" /></p>
<p><img src="MSthesisBook_files/figure-html/rarefaction%20curve-1.png" width="672" /></p>
<pre><code>##      Asym      xmid     slope 
## 77.085263 10.379364  2.104346</code></pre>
<pre><code>##  [1] 11.50164 17.50102 21.91169 25.41697 28.32076 30.79167 32.93486
##  [8] 34.82098 36.50003 38.00880 39.37519 40.62086 41.76300 42.81545
## [15] 43.78952</code></pre>
<p><img src="MSthesisBook_files/figure-html/rarefaction%20curve-2.png" width="672" /></p>
</div>
<div id="rarefaction-using-vegan" class="section level2">
<h2><span class="header-section-number">2.2</span> Rarefaction using Vegan</h2>
<p><img src="MSthesisBook_files/figure-html/Rarefaction-1.png" width="672" /><img src="MSthesisBook_files/figure-html/Rarefaction-2.png" width="672" /></p>
</div>
<div id="deriving-simpsons-diversity-index" class="section level2">
<h2><span class="header-section-number">2.3</span> Deriving Simpson’s Diversity Index</h2>
<pre><code>##       CA       CB       CC       CD       CE       PA       PB       PC 
## 1.418484 1.791759 1.810592 1.818166 2.031423 2.622996 1.727010 1.699258 
##       PD       PE       SA       SB       SC       SD       SE 
## 2.212530 1.637727 2.329190 1.881611 2.118527 2.313582 1.893788</code></pre>
</div>
<div id="lets-make-a-whittaker-plot" class="section level2">
<h2><span class="header-section-number">2.4</span> Lets make a Whittaker plot</h2>
<pre><code>## 
## Deviance for RAD models:
## 
##                  CA       CB       CC       CD       CE       PA       PB
## Null        1.02151  1.99618  9.84140  9.33551 10.05057  7.62813  2.74450
## Preemption  0.61915  0.86423  9.29821  8.84050  7.85160  5.01911  1.94073
## Lognormal   0.58399  0.54817  5.67034  5.51876  7.82598  3.69578  2.23844
## Zipf        0.48624  0.22520  2.54721  2.03484  6.15877  1.52559  1.92643
## Mandelbrot  0.42518  0.22520  2.54721  2.03484  5.19435  1.36864  1.46242
##                  PC       PD       PE       SA       SB       SC       SD
## Null        2.27229 10.00193  4.56753  5.51726 14.46778  5.68408  4.25790
## Preemption  2.07543  9.38198  4.32004  4.70656  7.42691  4.37264  2.94046
## Lognormal   1.23514  6.37543  3.20893  2.67068  3.95722  3.55080  2.34855
## Zipf        0.29946  2.99586  1.27231  0.53937  1.77644  1.87374  1.73316
## Mandelbrot  0.29946  2.99586  1.27232  0.53937  1.29200  1.51869  0.93167
##                SE
## Null       4.2249
## Preemption 2.5337
## Lognormal  1.8280
## Zipf       1.0940
## Mandelbrot 1.0940</code></pre>
<p><img src="MSthesisBook_files/figure-html/Whittaker%20vegan-1.png" width="672" /></p>
</div>
<div id="hypothesis-1-there-is-no-difference-in-bat-species-diversity-abundance-richness-between-forest-types" class="section level2">
<h2><span class="header-section-number">2.5</span> Hypothesis 1: There is no difference in bat species diversity, abundance, richness between forest types</h2>
<p>Lets get boxplots of the forest types
<img src="MSthesisBook_files/figure-html/boxplots%20of%20forest%20type-1.png" width="672" />
There appear to be outliers here. Let’s see conduct an anova between abundance and forest type. But first lets test assumptions.</p>
<pre><code>## [1] 141.5</code></pre>
<pre><code>## [1] 71.5</code></pre>
<pre><code>## [1] 321.8</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.5488 0.5914
##       12</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1$Abundance
## W = 0.95557, p-value = 0.6159</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, ]$Abundance
## W = 0.89691, p-value = 0.393</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, ]$Abundance
## W = 0.87606, p-value = 0.2918</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, ]$Abundance
## W = 0.94741, p-value = 0.7187</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  aov.abun.resid
## W = 0.98754, p-value = 0.9975</code></pre>
<p>The p-value is not less than .05 for either, assuming homogeneity of variances and normality.</p>
<p><img src="MSthesisBook_files/figure-html/abun%20and%20forest%20type-1.png" width="672" /><img src="MSthesisBook_files/figure-html/abun%20and%20forest%20type-2.png" width="672" /></p>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Forest.Type  2  574.5   287.3   1.611   0.24
## Residuals   12 2139.2   178.3</code></pre>
<p>Not significant (p= .24)</p>
<p>Now lets do the same for richness. First a boxplot:
<img src="MSthesisBook_files/figure-html/boxplot%20richness-1.png" width="672" /></p>
<p>Now assumptions:</p>
<pre><code>## [1] 13.2</code></pre>
<pre><code>## [1] 24.8</code></pre>
<pre><code>## [1] 8.2</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2   0.254 0.7798
##       12</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1$Richness
## W = 0.9586, p-value = 0.668</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, ]$Richness
## W = 0.91408, p-value = 0.4925</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, ]$Richness
## W = 0.77342, p-value = 0.04834</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, ]$Richness
## W = 0.80397, p-value = 0.08727</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  aov.rich.resid
## W = 0.93778, p-value = 0.3553</code></pre>
<p>The p-value is not less than .05 for either, assuming homogeneity of variances and normality.
<img src="MSthesisBook_files/figure-html/summary%20Richness-1.png" width="672" /><img src="MSthesisBook_files/figure-html/summary%20Richness-2.png" width="672" /></p>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Forest.Type  2  32.93   16.47   1.069  0.374
## Residuals   12 184.80   15.40</code></pre>
<p>Not significant (p-values=0.374)</p>
<p>Now lets do the same for diversity. First a boxplot:
<img src="MSthesisBook_files/figure-html/boxplot%20diversity-1.png" width="672" /></p>
<p>Now assumptions:</p>
<pre><code>## [1] 0.006321939</code></pre>
<pre><code>## [1] 0.002424467</code></pre>
<pre><code>## [1] 0.002775702</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.6115 0.5586
##       12</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1$diversitysitessimp
## W = 0.95772, p-value = 0.6528</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, ]$diversitysitessimp
## W = 0.92041, p-value = 0.5326</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, ]$diversitysitessimp
## W = 0.9067, p-value = 0.448</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, ]$diversitysitessimp
## W = 0.79006, p-value = 0.06708</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  aov.rich.resid
## W = 0.93778, p-value = 0.3553</code></pre>
<p>The p-value is not less than .05 for either, assuming homogeneity of variances and normality.
<img src="MSthesisBook_files/figure-html/summary%20diversitysitessimp-1.png" width="672" /><img src="MSthesisBook_files/figure-html/summary%20diversitysitessimp-2.png" width="672" /></p>
<pre><code>##             Df  Sum Sq  Mean Sq F value Pr(&gt;F)
## Forest.Type  2 0.00186 0.000929   0.242  0.789
## Residuals   12 0.04609 0.003841</code></pre>
<p>Not significant, p-value -0.789</p>
</div>
<div id="hypothesis-2-there-is-no-difference-in-number-of-feeding-guilds-between-forest-type" class="section level2">
<h2><span class="header-section-number">2.6</span> Hypothesis 2: There is no difference in number of feeding guilds between forest type</h2>
<p><img src="MSthesisBook_files/figure-html/h2%20feeding%20guild-1.png" width="672" />
Now assumptions:</p>
<pre><code>## [1] 1.2</code></pre>
<pre><code>## [1] 1.3</code></pre>
<pre><code>## [1] 0.3</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.3333  0.723
##       12</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1$Feeding.Guild
## W = 0.88103, p-value = 0.04916</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, ]$Feeding.Guild
## W = 0.82827, p-value = 0.135</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, ]$Feeding.Guild
## W = 0.96086, p-value = 0.814</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, ]$Feeding.Guild
## W = 0.68403, p-value = 0.00647</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  aov.fg.resid
## W = 0.95873, p-value = 0.6703</code></pre>
<p><img src="MSthesisBook_files/figure-html/feeding%20guild%20ass-1.png" width="672" />
While the variances are homogenous, feeding guild fails the shapiro-wilkes test. The QQ plot seems borderline, I will assume that this is non-parametric and use a kruskal-wallis test.</p>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Feeding.Guild by Forest.Type
## Kruskal-Wallis chi-squared = 4.5387, df = 2, p-value = 0.1034</code></pre>
<p>Not significant, p-value is .10
Ok, feeding guild itself is not significant, but what if we look at individual feeding guilds?
<img src="MSthesisBook_files/figure-html/bar%20chart%20of%20feeding%20guilds-1.png" width="672" />
High flying frugivores and low flying frugivores are both strongly represented. Lets test each one against forest type. First HFF:</p>
<p><img src="MSthesisBook_files/figure-html/HFF%20boxplot-1.png" width="672" />
SLR seems like it is different…
Lets test assumptions</p>
<pre><code>## [1] 42.3</code></pre>
<pre><code>## [1] 49.7</code></pre>
<pre><code>## [1] 66</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.0407 0.9603
##       12</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1$HFF
## W = 0.8997, p-value = 0.09417</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, ]$HFF
## W = 0.8034, p-value = 0.08634</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, ]$HFF
## W = 0.75661, p-value = 0.03423</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, ]$HFF
## W = 0.92034, p-value = 0.5321</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  aov.hff.resid
## W = 0.93866, p-value = 0.3658</code></pre>
<p><img src="MSthesisBook_files/figure-html/HFF%20ass-1.png" width="672" />
Assumptions are met.</p>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Forest.Type  2  179.7   89.87   1.706  0.223
## Residuals   12  632.0   52.67</code></pre>
<p>Not significant, p-value=0.223. I find this curious, it seems like this would have been significant.
Now lets try LFF.
<img src="MSthesisBook_files/figure-html/LFF%20boxplot-1.png" width="672" />
Less distinct trend than HFF.
Lets test assumptions:</p>
<pre><code>## [1] 37.5</code></pre>
<pre><code>## [1] 12.8</code></pre>
<pre><code>## [1] 102.7</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1$LFF
## W = 0.89037, p-value = 0.06793</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, ]$LFF
## W = 0.85055, p-value = 0.1963</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, ]$LFF
## W = 0.94265, p-value = 0.6847</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, ]$LFF
## W = 0.93847, p-value = 0.6552</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  aov.LFF.resid
## W = 0.96034, p-value = 0.6984</code></pre>
<p><img src="MSthesisBook_files/figure-html/LFF%20ass-1.png" width="672" />
Assumptions met.</p>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Forest.Type  2  120.4    60.2    1.18   0.34
## Residuals   12  612.0    51.0</code></pre>
<p>Not significant 0.34.
Lets try the next three highest feeding guilds, OMG (omnivorous nectarivore), OMP (omnivorous predator), ICF (insecti-carnivore).</p>
<p><img src="MSthesisBook_files/figure-html/other%20feeding%20guilds%20box-1.png" width="672" /></p>
<pre><code>## [[1]]
## NULL
## 
## [[2]]
## NULL
## 
## [[3]]
## NULL</code></pre>
<p>Nothing pops out too much here
Lets test assumptions:</p>
<pre><code>## [1] 0.5
## [1] 0.3
## [1] 1.5
## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.6154 0.5566
##       12               
## [1] &quot;OMG Levene test not significant, doesnt violate assumptions levene.OMG&quot;
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, bcols[[i]]]
## W = 0.88349, p-value = 0.3254
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, bcols[[i]]]
## W = 0.68403, p-value = 0.00647
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, bcols[[i]]]
## W = 0.83274, p-value = 0.1458
## 
## [1] &quot;OMG shapiro test is SIGNIFICANT, violates assumptions of normality, 0.00278346134928008&quot;</code></pre>
<pre><code>## NULL
## [1] 1
## [1] 1.7
## [1] 2
## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.0741  0.929
##       12               
## [1] &quot;ICG Levene test not significant, doesnt violate assumptions levene.ICG&quot;
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, bcols[[i]]]
## W = 0.82083, p-value = 0.1185
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, bcols[[i]]]
## W = 0.90202, p-value = 0.4211
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, bcols[[i]]]
## W = 0.76672, p-value = 0.0422</code></pre>
<pre><code>## NULL
## [1] 2.5
## [1] 0.2
## [1] 1.7
## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  1.4615 0.2704
##       12               
## [1] &quot;OMP Levene test not significant, doesnt violate assumptions levene.OMP&quot;
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, bcols[[i]]]
## W = 0.98676, p-value = 0.9672
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, bcols[[i]]]
## W = 0.55218, p-value = 0.000131
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, bcols[[i]]]
## W = 0.73477, p-value = 0.02138
## 
## [1] &quot;OMP shapiro test is SIGNIFICANT, violates assumptions of normality, 0.00114765455493928&quot;</code></pre>
<p><img src="MSthesisBook_files/figure-html/other%20feeding%20guild%20ass-1.png" width="672" /></p>
<pre><code>## NULL</code></pre>
<p>OMP and OMG violate assumption of normality, while ICG does not. I will use a KW test for OMP and OMG</p>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  OMP by Forest.Type
## Kruskal-Wallis chi-squared = 4.4943, df = 2, p-value = 0.1057</code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  OMG by Forest.Type
## Kruskal-Wallis chi-squared = 1.797, df = 2, p-value = 0.4072</code></pre>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)
## b1$Forest.Type  2    2.8   1.400   0.894  0.435
## Residuals      12   18.8   1.567</code></pre>
<p>Nothing significant here! These were abundances. What about richness of the specific feeding guilds?</p>
<pre><code>## [[1]]
## NULL
## 
## [[2]]
## NULL
## 
## [[3]]
## NULL
## 
## [[4]]
## NULL
## 
## [[5]]
## NULL</code></pre>
<p><img src="MSthesisBook_files/figure-html/fg%20richness%20box-1.png" width="672" />
Interesting, now lets check assumptions:</p>
<pre><code>## [1] 11.2
## [1] 1.2
## [1] 3.8
## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  2.1724 0.1566
##       12               
## [1] &quot;HFF.rich Levene test not significant, doesnt violate assumptions levene.HFF.rich&quot;
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, bcols[[i]]]
## W = 0.95003, p-value = 0.7374
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, bcols[[i]]]
## W = 0.68403, p-value = 0.00647
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, bcols[[i]]]
## W = 0.95296, p-value = 0.7583</code></pre>
<pre><code>## NULL
## [1] 1
## [1] 0.3
## [1] 1.2
## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.4615  0.641
##       12               
## [1] &quot;LFF.rich Levene test not significant, doesnt violate assumptions levene.LFF.rich&quot;
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, bcols[[i]]]
## W = 0.82083, p-value = 0.1185
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, bcols[[i]]]
## W = 0.68403, p-value = 0.00647
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, bcols[[i]]]
## W = 0.82827, p-value = 0.135</code></pre>
<pre><code>## NULL
## [1] 0.3
## [1] 0.8
## [1] 0.2
## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.4615  0.641
##       12               
## [1] &quot;OMG.rich Levene test not significant, doesnt violate assumptions levene.OMG.rich&quot;
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, bcols[[i]]]
## W = 0.68403, p-value = 0.00647
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, bcols[[i]]]
## W = 0.77091, p-value = 0.04595
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, bcols[[i]]]
## W = 0.55218, p-value = 0.000131
## 
## [1] &quot;OMG.rich shapiro test is SIGNIFICANT, violates assumptions of normality, 0.00347259820441093&quot;</code></pre>
<p><img src="MSthesisBook_files/figure-html/fg%20richness%20ass-1.png" width="672" /></p>
<pre><code>## NULL
## [1] 1.8
## [1] 1.2
## [1] 0.5
## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.6667 0.5314
##       12               
## [1] &quot;ICG.rich Levene test not significant, doesnt violate assumptions levene.ICG.rich&quot;
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, bcols[[i]]]
## W = 0.85191, p-value = 0.2006
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, bcols[[i]]]
## W = 0.82827, p-value = 0.135
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, bcols[[i]]]
## W = 0.88349, p-value = 0.3254
## 
## [1] &quot;ICG.rich shapiro test is SIGNIFICANT, violates assumptions of normality, 0.038138920253506&quot;</code></pre>
<pre><code>## NULL
## [1] 0.7
## [1] 0.8
## [1] 1.2
## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2   0.087 0.9173
##       12               
## [1] &quot;OMP.rich Levene test not significant, doesnt violate assumptions levene.OMP.rich&quot;
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;CCR&quot;, bcols[[i]]]
## W = 0.88104, p-value = 0.314
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;PCR&quot;, bcols[[i]]]
## W = 0.77091, p-value = 0.04595
## 
## 
##  Shapiro-Wilk normality test
## 
## data:  b1[b1$Forest.Type == &quot;SLR&quot;, bcols[[i]]]
## W = 0.68403, p-value = 0.00647
## 
## [1] &quot;OMP.rich shapiro test is SIGNIFICANT, violates assumptions of normality, 0.000585948132815366&quot;</code></pre>
<pre><code>## NULL</code></pre>
<p><img src="MSthesisBook_files/figure-html/fg%20richness%20ass-2.png" width="672" />
HFF.rich, LFF.rich meet assumptions. OMG.rich, ICG.rich, OMP.rich violate assumption of normality, I will use a KW test on them.</p>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)
## b1$Forest.Type  2   2.13   1.067   0.198  0.823
## Residuals      12  64.80   5.400</code></pre>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)  
## b1$Forest.Type  2  5.733  2.8667    3.44 0.0659 .
## Residuals      12 10.000  0.8333                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  OMP.rich by Forest.Type
## Kruskal-Wallis chi-squared = 0.18788, df = 2, p-value = 0.9103</code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  OMG.rich by Forest.Type
## Kruskal-Wallis chi-squared = 3.8949, df = 2, p-value = 0.1426</code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  ICG.rich by Forest.Type
## Kruskal-Wallis chi-squared = 0.23608, df = 2, p-value = 0.8887</code></pre>
<p>Nothing significant here, although LFF.rich is close (p=.0659)</p>
</div>
<div id="hypothesis-3-there-is-no-relationship-between-abundances-of-individual-species-and-forest-type" class="section level2">
<h2><span class="header-section-number">2.7</span> Hypothesis 3: There is no relationship between Abundances of Individual species and forest type</h2>
<p><div id="htmlwidget-0b06d1019b2a318b4b91" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-0b06d1019b2a318b4b91">{"x":{"data":[{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.900000000000002,0.900000000000006,0.900000000000006,0.900000000000006,0.900000000000006,0.900000000000006,0.900000000000006,0.900000000000006,0.900000000000006,0.900000000000006,0.900000000000006,0.900000000000006,0.900000000000006],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44],"y":[150,53,43,20,18,17,12,9,9,7,7,7,7,7,6,6,5,5,4,3,3,3,3,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"text":["Species: Carollia brevicauda<br />Count: 150","Species: Artibeus planirostris<br />Count:  53","Species: Artibeus lituratus<br />Count:  43","Species: Carollia perspicallata<br />Count:  20","Species: Uroderma bilobatum<br />Count:  18","Species: Platyrrhinus infuscus<br />Count:  17","Species: Rhinophylla pumillio<br />Count:  12","Species: Sturnira tildae<br />Count:   9","Species: Platyrrhinus incarum<br />Count:   9","Species: Carollia benkeithi<br />Count:   7","Species: Glossophaga soricina<br />Count:   7","Species: Phylosstomus hastatus<br />Count:   7","Species: Lophostoma silvilocum<br />Count:   7","Species: Artibeus gnomus<br />Count:   7","Species: Myotis riparius<br />Count:   6","Species: Vampyrodes caraccioli<br />Count:   6","Species: Phylosstomus elongatus<br />Count:   5","Species: Lonchophylla thomasi<br />Count:   5","Species: Mesophylla macconneli<br />Count:   4","Species: Artibeus cinereus<br />Count:   3","Species: Artibeus obscurus<br />Count:   3","Species: Mimon crenulatum<br />Count:   3","Species: Vampyressa pusilla<br />Count:   3","Species: Dermanura glaucus??<br />Count:   2","Species: Micronycteris minuta<br />Count:   2","Species: Phylloderma stenops<br />Count:   2","Species: Desmodus rotundus<br />Count:   2","Species: Micronycteris megalotis<br />Count:   2","Species: Molossus molossus<br />Count:   2","Species: Phylosstomus discolor<br />Count:   1","Species: Myotis keaysie<br />Count:   1","Species: Eptesicus brasiliensis<br />Count:   1","Species: Vampyriscus brocki<br />Count:   1","Species: Micronycteris microtis<br />Count:   1","Species: Platyrrhinus helleri<br />Count:   1","Species: Lampronycteris brachyotis<br />Count:   1","Species: Tonatia bidens<br />Count:   1","Species: Dermanura anderseni?<br />Count:   1","Species: Micronycteris hirsuta<br />Count:   1","Species: Vampyrum spectrum<br />Count:   1","Species: Saccopteryx bilineata<br />Count:   1","Species: Chrotopterus auritus<br />Count:   1","Species: Vampyriscus bidens<br />Count:   1","Species: Lophostoma brasiliense<br />Count:   1"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(89,89,89,1)","line":{"width":1.88976377952756,"color":"transparent"}},"showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.2283105022831,"r":7.30593607305936,"b":174.611872146119,"l":43.1050228310502},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.4,44.6],"tickmode":"array","ticktext":["Carollia brevicauda","Artibeus planirostris","Artibeus lituratus","Carollia perspicallata","Uroderma bilobatum","Platyrrhinus infuscus","Rhinophylla pumillio","Sturnira tildae","Platyrrhinus incarum","Carollia benkeithi","Glossophaga soricina","Phylosstomus hastatus","Lophostoma silvilocum","Artibeus gnomus","Myotis riparius","Vampyrodes caraccioli","Phylosstomus elongatus","Lonchophylla thomasi","Mesophylla macconneli","Artibeus cinereus","Artibeus obscurus","Mimon crenulatum","Vampyressa pusilla","Dermanura glaucus??","Micronycteris minuta","Phylloderma stenops","Desmodus rotundus","Micronycteris megalotis","Molossus molossus","Phylosstomus discolor","Myotis keaysie","Eptesicus brasiliensis","Vampyriscus brocki","Micronycteris microtis","Platyrrhinus helleri","Lampronycteris brachyotis","Tonatia bidens","Dermanura anderseni?","Micronycteris hirsuta","Vampyrum spectrum","Saccopteryx bilineata","Chrotopterus auritus","Vampyriscus bidens","Lophostoma brasiliense"],"tickvals":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44],"categoryorder":"array","categoryarray":["Carollia brevicauda","Artibeus planirostris","Artibeus lituratus","Carollia perspicallata","Uroderma bilobatum","Platyrrhinus infuscus","Rhinophylla pumillio","Sturnira tildae","Platyrrhinus incarum","Carollia benkeithi","Glossophaga soricina","Phylosstomus hastatus","Lophostoma silvilocum","Artibeus gnomus","Myotis riparius","Vampyrodes caraccioli","Phylosstomus elongatus","Lonchophylla thomasi","Mesophylla macconneli","Artibeus cinereus","Artibeus obscurus","Mimon crenulatum","Vampyressa pusilla","Dermanura glaucus??","Micronycteris minuta","Phylloderma stenops","Desmodus rotundus","Micronycteris megalotis","Molossus molossus","Phylosstomus discolor","Myotis keaysie","Eptesicus brasiliensis","Vampyriscus brocki","Micronycteris microtis","Platyrrhinus helleri","Lampronycteris brachyotis","Tonatia bidens","Dermanura anderseni?","Micronycteris hirsuta","Vampyrum spectrum","Saccopteryx bilineata","Chrotopterus auritus","Vampyriscus bidens","Lophostoma brasiliense"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-90,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"Species","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-7.5,157.5],"tickmode":"array","ticktext":["0","50","100","150"],"tickvals":[0,50,100,150],"categoryorder":"array","categoryarray":["0","50","100","150"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"# of captures","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","showSendToCloud":false},"source":"A","attrs":{"dfda6beb71ce":{"x":{},"y":{},"type":"bar"}},"cur_data":"dfda6beb71ce","visdat":{"dfda6beb71ce":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
Three species are most abundant: C. brevicauda, A. planirostris, and A. lituratus. Lets use these for analysis.
<img src="MSthesisBook_files/figure-html/3%20species%20box-1.png" width="672" /></p>
<pre><code>## [[1]]
## NULL
## 
## [[2]]
## NULL
## 
## [[3]]
## NULL</code></pre>
<p>Now assumptions:</p>
<pre><code>## [1] 28.8
## [1] 7
## [1] 65.3
## [1] &quot;Carollia.brevicaudaLevene test not significant, doesnt violate assumptions levene.Carollia.brevicauda&quot;
## [1] &quot;Carollia.brevicauda shapiro test is SIGNIFICANT, violates assumptions of normality, 0.0127212499331806&quot;</code></pre>
<pre><code>## NULL
## [1] 8.3
## [1] 8.7
## [1] 11.2
## [1] &quot;Artibeus.lituratusLevene test not significant, doesnt violate assumptions levene.Artibeus.lituratus&quot;
## [1] &quot;Artibeus.lituratus shapiro test is SIGNIFICANT, violates assumptions of normality, 0.0270141488491566&quot;</code></pre>
<pre><code>## NULL
## [1] 11.2
## [1] 4.3
## [1] 19.5
## [1] &quot;Artibeus.planirostrisLevene test not significant, doesnt violate assumptions levene.Artibeus.planirostris&quot;
## [1] &quot;Artibeus.planirostris shapiro test is SIGNIFICANT, violates assumptions of normality, 0.0446404159569824&quot;</code></pre>
<p><img src="MSthesisBook_files/figure-html/3spp%20ass-1.png" width="672" /></p>
<pre><code>## NULL</code></pre>
<p>All three violate assumption of normality, so I will use a KW test.</p>
<pre><code>## [1] &quot;Carollia.brevicauda&quot;
## 
##  Kruskal-Wallis rank sum test
## 
## data:  get(i) by Forest.Type
## Kruskal-Wallis chi-squared = 1.6831, df = 2, p-value = 0.431
## 
## [1] &quot;Artibeus.lituratus&quot;
## 
##  Kruskal-Wallis rank sum test
## 
## data:  get(i) by Forest.Type
## Kruskal-Wallis chi-squared = 1.1985, df = 2, p-value = 0.5492
## 
## [1] &quot;Artibeus.planirostris&quot;
## 
##  Kruskal-Wallis rank sum test
## 
## data:  get(i) by Forest.Type
## Kruskal-Wallis chi-squared = 2.0936, df = 2, p-value = 0.3511</code></pre>
<p>Darn, nothing significant here either.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["MSthesisBook.pdf", "MSthesisBook.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
